name: Publish Docker Images
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  brownie-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install eth-brownie
      
      - name: Install Ganache CLI
        run: npm install -g ganache-cli
      
      - name: Run Brownie tests with parallel execution
        run: |
              brownie test -v --tb=short -n auto

  build-and-push:
    runs-on: ubuntu-latest
    needs: brownie-tests  # This ensures tests pass before building/pushing
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build all images with Compose
        run: docker compose build
      
      - name: List Docker images
        run: docker images
      
      - name: Tag and push each service
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/lotterychain_hardhat
          docker push ${{ secrets.DOCKER_USERNAME }}/lotterychain_deploy
          docker push ${{ secrets.DOCKER_USERNAME }}/lotterychain_react
